// mongoose model enums
const ORDER_PENDING = "PENDING";
const ORDER_CONFIRMED = "CONFIRMED";
const ORDER_READY = "READY";
const ORDER_FULFILLED = "FULFILLED";
const ORDER_CANCELLED = "CANCELLED";
const ORDER_PAST = "PAST";

const VAN_OPEN = "OPEN";
const VAN_CLOSED = "CLOSED";

module.exports = {
	ORDER_PENDING,
	ORDER_CONFIRMED,
	ORDER_READY,
	ORDER_FULFILLED,
	ORDER_CANCELLED,
	ORDER_PAST,
	VAN_OPEN,
	VAN_CLOSED,
};
